"""empty message

Revision ID: c0faa9990210
Revises: e3724877e8cf
Create Date: 2017-10-18 11:04:01.789974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0faa9990210'
down_revision = 'e3724877e8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('marked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'marked')
    # ### end Alembic commands ###
